version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: bunasiem-db
    environment:
      POSTGRES_DB: bunasiem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: bunasiem-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/bunasiem
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: bunasiem-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: