version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: bunasiem-db
    environment:
      POSTGRES_DB: bunasiem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - bunasiem-network

volumes:
  postgres_data:

networks:
  bunasiem-network:
    driver: bridge